apiVersion: v1
kind: Service
metadata:
  name: test-backend
  labels:
    app: test-backend
spec:
  selector:
    app: test-backend
  ports:
    - port: 80
      targetPort: 3000
      name: http
  type: NodePort
